name: imdumb
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  firebase_core: ^4.5.0
  firebase_remote_config: ^6.2.0
  shared_preferences: ^2.5.4
  dio: ^5.9.2
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  hive_flutter: ^1.1.0
  firebase_database: ^12.1.4
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  adaptive_icon_background: "#030712"
  adaptive_icon_foreground: assets/images/icon.png
  remove_alpha_ios: true  # Requerido para App Store (no permite transparencia en el icono)

flutter:

  uses-material-design: true

  assets:
    - .env.stage
    - .env.prod
    - assets/images/imageNotFound.png
    - assets/images/categorias_image.png
    - assets/images/icon.png

  fonts:
    - family: Junegull
      fonts:
        - asset: assets/fonts/junegull.ttf
    - family: Typo Round
      fonts:
        - asset: assets/typo-round/Typo_Round_Thin_Demo.otf
          weight: 100
        - asset: assets/typo-round/Typo_Round_Thin_Italic Demo.otf
          weight: 100
          style: italic
        - asset: assets/typo-round/Typo_Round_Light_Demo.otf
          weight: 300
        - asset: assets/typo-round/Typo_Round_Light_Italic_Demo.otf
          weight: 300
          style: italic
        - asset: assets/typo-round/Typo_Round_Regular_Demo.otf
          weight: 400
        - asset: assets/typo-round/Typo_Round_Italic_Demo.otf
          weight: 400
          style: italic
        - asset: assets/typo-round/Typo_Round_Bold_Demo.otf
          weight: 700
        - asset: assets/typo-round/Typo_Round_Bold_Italic_Demo.otf
          weight: 700
          style: italic
